import { QuestionItem } from './types';

// Data transcribed and extrapolated from the provided image
export const DATASET: QuestionItem[] = [
  // 官方样题 01
  { id: 1, source: "官方样题01", code: "M1C1Q9", point: "purpose/inference", question: "What does the woman imply that she was about to do?" },
  { id: 2, source: "官方样题01", code: "M1C1Q10", point: "inference/idiom", question: "Why does the man say 'I'd forget my head if it wasn't screwed on'?" },
  { id: 3, source: "官方样题01", code: "M1C2Q11", point: "purpose", question: "Why did the woman call a technician?" },
  { id: 4, source: "官方样题01", code: "M1C2Q12", point: "suggestion", question: "What does the woman suggest the man do?" },
  { id: 5, source: "官方样题01", code: "M1A1Q13", point: "main idea", question: "What is the announcement about?" },
  { id: 6, source: "官方样题01", code: "M1A1Q14", point: "purpose", question: "Why does the professor mention Dr. Palmer's popularity?" },
  { id: 7, source: "官方样题01", code: "M2C3Q9", point: "purpose", question: "What is the man trying to decide between?" },
  { id: 8, source: "官方样题01", code: "M2C3Q10", point: "reasons", question: "What reason does the woman give for her suggestion?" },
  { id: 9, source: "官方样题01", code: "M2A2Q11", point: "purpose", question: "What is the main purpose of the announcement?" },
  { id: 10, source: "官方样题01", code: "M2A2Q12", point: "suggestion", question: "What should students do during the closure?" },

  // 官方样题 02
  { id: 11, source: "官方样题02", code: "M1C1Q9", point: "purpose", question: "What problem is the man experiencing with his laptop?" },
  { id: 12, source: "官方样题02", code: "M1C1Q10", point: "next move", question: "What will the man most likely do next?" },
  { id: 13, source: "官方样题02", code: "M1C2Q11", point: "purpose", question: "What is the man's problem?" },
  { id: 14, source: "官方样题02", code: "M1C2Q12", point: "inference/idiom", question: "What does the woman imply when she says, 'I stocked up yesterday'?" },
  { id: 15, source: "官方样题02", code: "M1A1Q13", point: "purpose", question: "Why does the speaker mention family?" },
  { id: 16, source: "官方样题02", code: "M1A1Q14", point: "suggestion", question: "What does the speaker encourage the participants to do?" },
  { id: 17, source: "官方样题02", code: "M2C3Q9", point: "inference", question: "What was the woman not aware of?" },
  { id: 18, source: "官方样题02", code: "M2C3Q10", point: "next move", question: "What will the woman probably do next?" },
  { id: 19, source: "官方样题02", code: "M2A2Q11", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 20, source: "官方样题02", code: "M2A2Q12", point: "suggestion", question: "What does the speaker hope the listeners will do?" },

  // 官方模考题 01
  { id: 21, source: "官方模考题01", code: "M1C1Q9", point: "purpose", question: "Why did the man miss an event?" },
  { id: 22, source: "官方模考题01", code: "M1C1Q10", point: "suggestion", question: "What does the woman encourage the man to do?" },
  { id: 23, source: "官方模考题01", code: "M1C2Q11", point: "purpose", question: "What does the woman want to do before an exercise class?" },
  { id: 24, source: "官方模考题01", code: "M1C2Q12", point: "inference", question: "What can be inferred about the man?" },
  { id: 25, source: "官方模考题01", code: "M1A1Q13", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 26, source: "官方模考题01", code: "M1A1Q14", point: "suggestion", question: "What does the speaker hope the listeners will do?" },
  { id: 27, source: "官方模考题01", code: "M1A2Q15", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 28, source: "官方模考题01", code: "M1A2Q16", point: "suggestion", question: "What does the speaker suggest members bring?" },
  { id: 29, source: "官方模考题01", code: "M2C3Q4", point: "main idea", question: "What event are the speakers planning to attend?" },
  { id: 30, source: "官方模考题01", code: "M2C3Q5", point: "detail", question: "What does the woman plan to bring to the event?" },
  { id: 31, source: "官方模考题01", code: "M2C4Q6", point: "main idea", question: "What event are the speakers discussing?" },
  { id: 32, source: "官方模考题01", code: "M2C4Q7", point: "detail", question: "What does the man hope to find at the event?" },

  // 官方模考题 02
  { id: 33, source: "官方模考题02", code: "M1C1Q9", point: "reasons", question: "Why is the man running late?" },
  { id: 34, source: "官方模考题02", code: "M1C1Q10", point: "next move", question: "What will the woman probably do next?" },
  { id: 35, source: "官方模考题02", code: "M1C2Q11", point: "reasons", question: "Why is the man asking about a place to eat?" },
  { id: 36, source: "官方模考题02", code: "M1C2Q12", point: "inference", question: "What can be inferred about the man?" },
  { id: 37, source: "官方模考题02", code: "M1A1Q13", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 38, source: "官方模考题02", code: "M1A1Q14", point: "suggestion", question: "What does the speaker hope the listeners will do?" },
  { id: 39, source: "官方模考题02", code: "M1A1Q15", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 40, source: "官方模考题02", code: "M1A1Q16", point: "suggestion", question: "What does the speaker suggest members bring?" },
  { id: 41, source: "官方模考题02", code: "M2C3Q4", point: "main idea", question: "What event are the speakers planning to attend?" },
  { id: 42, source: "官方模考题02", code: "M2C3Q5", point: "detail (时间)", question: "When will the event begin?" },
  { id: 43, source: "官方模考题02", code: "M2C4Q6", point: "main idea", question: "What event are the speakers discussing?" },
  { id: 44, source: "官方模考题02", code: "M2C4Q7", point: "reasons", question: "What is the woman interested in the event?" },

  // 官方模考题 03
  { id: 45, source: "官方模考题03", code: "M1C1Q13", point: "reasons", question: "Why does the woman encourage the man to complete a task today?" },
  { id: 46, source: "官方模考题03", code: "M1C1Q14", point: "inference", question: "What does the man say about a neighbor?" },
  { id: 47, source: "官方模考题03", code: "M1C2Q15", point: "purpose", question: "What is the man looking for?" },
  { id: 48, source: "官方模考题03", code: "M1C2Q16", point: "suggestion", question: "What genre does the woman suggest?" },
  { id: 49, source: "官方模考题03", code: "M1C3Q17", point: "detail (重复强调)", question: "What kind of fitness class does the man mention?" },
  { id: 50, source: "官方模考题03", code: "M1C3Q18", point: "opinion", question: "What does the man say about the instructors?" },
  { id: 51, source: "官方模考题03", code: "M1A1Q19", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 52, source: "官方模考题03", code: "M1A1Q20", point: "suggestion", question: "What are students encouraged to do?" },
  { id: 53, source: "官方模考题03", code: "M1A2Q21", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 54, source: "官方模考题03", code: "M1A2Q22", point: "suggestion", question: "What are students encouraged to do?" },
  { id: 55, source: "官方模考题03", code: "M1A3Q23", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 56, source: "官方模考题03", code: "M1A3Q24", point: "suggestion", question: "What does the speaker hope the listeners will do?" },
  { id: 57, source: "官方模考题03", code: "M1A4Q25", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 58, source: "官方模考题03", code: "M1A4Q26", point: "suggestion", question: "What does the speaker hope the listeners will do?" },
  { id: 59, source: "官方模考题03", code: "M2A1Q4", point: "reasons", question: "Why is the woman going to the gym in the evening?" },
  { id: 60, source: "官方模考题03", code: "M2A1Q5", point: "opinion", question: "What is the man's attitude toward exercising?" },
  { id: 61, source: "官方模考题03", code: "M2A2Q6", point: "main idea", question: "What are the speakers mainly discussing?" },
  { id: 62, source: "官方模考题03", code: "M2A2Q7", point: "inference", question: "What department of the company does the man most likely work in?" },

  // 官方模考题 04
  { id: 63, source: "官方模考题04", code: "M1C1Q13", point: "purpose", question: "What is the man planning to renovate?" },
  { id: 64, source: "官方模考题04", code: "M1C1Q14", point: "suggestion", question: "What does the woman suggest the man do first?" },
  { id: 65, source: "官方模考题04", code: "M1C2Q15", point: "main idea", question: "What did the woman do this morning?" },
  { id: 66, source: "官方模考题04", code: "M1C2Q16", point: "reasons", question: "Why do the speakers want to leave early?" },
  { id: 67, source: "官方模考题04", code: "M1C3Q17", point: "detail", question: "Where will the conference be held?" },
  { id: 68, source: "官方模考题04", code: "M1C3Q18", point: "detail", question: "What does the woman say about catering services?" },
  { id: 69, source: "官方模考题04", code: "M1A1Q19", point: "main idea", question: "What is the main purpose of the announcement?" },
  { id: 70, source: "官方模考题04", code: "M1A1Q20", point: "suggestion", question: "What should students do according to the announcement?" },
  { id: 71, source: "官方模考题04", code: "M1A2Q21", point: "detail (feature)", question: "Which of the following is true about the mentorship program?" },
  { id: 72, source: "官方模考题04", code: "M1A2Q22", point: "detail", question: "What should a student submit when signing up?" },
  { id: 73, source: "官方模考题04", code: "M1A3Q23", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 74, source: "官方模考题04", code: "M1A3Q24", point: "suggestion", question: "What does the speaker hope the listeners will do?" },
  { id: 75, source: "官方模考题04", code: "M1A4Q25", point: "main idea", question: "What is the main topic of the announcement?" },
  { id: 76, source: "官方模考题04", code: "M1A4Q26", point: "suggestion", question: "What are students encouraged to do?" },
  { id: 77, source: "官方模考题04", code: "M2C4Q4", point: "reasons", question: "Why is the man planning to go to the library?" },
  { id: 78, source: "官方模考题04", code: "M2C4Q5", point: "suggestion", question: "What is the woman's advice about studying?" },
  { id: 79, source: "官方模考题04", code: "M2C5Q6", point: "detail", question: "What is the woman's problem with her Internet?" },
  { id: 80, source: "官方模考题04", code: "M2C5Q7", point: "suggestion", question: "What does the man advise the woman to do?" },
  
  // 官方模考题 05
  { id: 81, source: "官方模考题05", code: "M1C1Q9", point: "purpose", question: "Why does the student go to see the professor?" },
  { id: 82, source: "官方模考题05", code: "M1C1Q10", point: "detail", question: "What does the professor say about the student's paper?" },
  { id: 83, source: "官方模考题05", code: "M1C2Q11", point: "inference", question: "What does the woman imply about the library policy?" },
  { id: 84, source: "官方模考题05", code: "M1C2Q12", point: "next move", question: "What will the man probably do next?" },
  { id: 85, source: "官方模考题05", code: "M1A1Q13", point: "main idea", question: "What is the lecture mainly about?" },
  { id: 86, source: "官方模考题05", code: "M1A1Q14", point: "detail", question: "According to the professor, what is a key feature of this period?" },
  { id: 87, source: "官方模考题05", code: "M1A2Q15", point: "purpose", question: "Why does the professor mention the experiment?" },
  { id: 88, source: "官方模考题05", code: "M1A2Q16", point: "opinion", question: "What is the professor's opinion on the theory?" },
  { id: 89, source: "官方模考题05", code: "M2C3Q4", point: "main idea", question: "What are the speakers mainly discussing?" },
  { id: 90, source: "官方模考题05", code: "M2C3Q5", point: "reasons", question: "Why does the man suggest taking the bus?" },
  { id: 91, source: "官方模考题05", code: "M2C4Q6", point: "detail", question: "What problem does the woman have with her schedule?" },
  { id: 92, source: "官方模考题05", code: "M2C4Q7", point: "suggestion", question: "What does the man suggest the woman do?" },
  { id: 93, source: "官方模考题05", code: "M2A1Q8", point: "inference", question: "What does the professor imply about the future of this technology?" },
  { id: 94, source: "官方模考题05", code: "M2A1Q9", point: "detail", question: "What resulted from the change in temperature?" },
];